version: '2'
services:
    training-app:
        image: training
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://training-mysql:3306/training?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    training-mysql:
        extends:
            file: mysql.yml
            service: training-mysql
